#!/usr/bin/env bun
/**
 * Walks apps/web/dist and writes apps/server/src/generated/staticFiles.ts
 * with one `import … with { type: "file" }` per asset. Bun picks those up
 * during `bun build --compile` and embeds the bytes into the executable.
 *
 * The emitted module exports a `Map<urlPath, bundlerPath>` consumed by
 * apps/server/src/standalone.ts.
 */
import { existsSync } from 'node:fs';
import { readdir } from 'node:fs/promises';
import { join, relative, resolve } from 'node:path';

const repoRoot = resolve(import.meta.dir, '..');
const webDist = resolve(repoRoot, 'apps/web/dist');
const outFile = resolve(repoRoot, 'apps/server/src/generated/staticFiles.ts');

async function* walk(dir: string): AsyncGenerator<string> {
  const entries = await readdir(dir, { withFileTypes: true });
  for (const entry of entries) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) {
      yield* walk(full);
    } else if (entry.isFile()) {
      yield full;
    }
  }
}

const files: string[] = [];
if (existsSync(webDist)) {
  for await (const file of walk(webDist)) {
    files.push(file);
  }
  files.sort();
} else {
  // No web build present — emit an empty stub so `tsc` can resolve the
  // import. The real manifest is regenerated by build:standalone.
  console.log(`No ${webDist} — writing empty stub.`);
}

const header = `// AUTO-GENERATED by scripts/generate-static-manifest.ts — do not edit by hand.\n`;
const imports: string[] = [];
const entries: string[] = [];

files.forEach((file, index) => {
  const urlPath = '/' + relative(webDist, file).replace(/\\/g, '/');
  const importPath = '../../../../apps/web/dist/' + relative(webDist, file).replace(/\\/g, '/');
  const ident = `f${index}`;
  imports.push(`import ${ident} from '${importPath}' with { type: 'file' };`);
  entries.push(`  [${JSON.stringify(urlPath)}, asPath(${ident})],`);
});

const helper = `// Bun embeds these imports as runtime path strings, but some of\n// \`@types/bun\`'s module declarations (e.g. HTMLBundle) say otherwise.\n// Coerce to string so the Map<string, string> stays honest.\nconst asPath = (v: unknown): string => v as string;\n`;

const body = imports.join('\n');
const map = `export const staticFiles = new Map<string, string>([\n${entries.join('\n')}\n]);\n`;

const source = `${header}${body}\n\n${helper}\n${map}`;
await Bun.write(outFile, source);

console.log(`Wrote ${outFile} with ${files.length} entries.`);
